name: 🐛 Bug report
description: Reportar un fallo con datos accionables
title: "[BUG] "
labels: [ "type/bug", "status/needs-triage" ]
body:
  - type: textarea
    id: what
    attributes: { label: ¿Qué ocurre?, description: ¿Qué esperabas?, placeholder: "Describe el bug…" }
    validations: { required: true }
  - type: input
    id: url
    attributes: { label: URL objetivo (si aplica) }
  - type: input
    id: python
    attributes: { label: Versión de Python }
  - type: textarea
    id: steps
    attributes: { label: Pasos para reproducir, placeholder: "1… 2… 3…" }
    validations: { required: true }
  - type: textarea
    id: logs
    attributes: { label: Logs/stacktrace relevantes }