name: CI
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: { python-version: [ "3.10", "3.11" ] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python-version }}-
      - name: Install deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          pip install ruff || true
          pip install mypy || true
          pip install pytest || true
      - name: Ruff (lint)
        run: |
          ruff --version
          ruff check . || (echo "::warning::Ruff reported issues"; exit 1)
      - name: mypy (soft-fail)
        if: ${{ hashFiles('**/*.py') != '' }}
        run: mypy --ignore-missing-imports || echo "::warning::mypy warnings (soft-fail)"
      - name: pytest (only if tests exist)
        if: ${{ hashFiles('tests/**') != '' }}
        run: pytest -q
