# .github/workflows/ci.yml
name: Python Scraper CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps

    - name: Run tests (placeholder)
      run: |
        echo "No tests defined yet. Placeholder step."

    - name: Check if crawler can start (dry-run)
      run: |
        # Use -m to run as a module, which is the correct way for packages.
        # Use --help to test if the entry point works without starting a full crawl.
        python -m src.main --help
