name: Nightly Smoke (Scraper+Metrics)
on:
  schedule: [ { cron: "0 4 * * *" } ]
  workflow_dispatch:
concurrency: { group: smoke-${{ github.ref }}, cancel-in-progress: true }
jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run smoke to toscrape
        run: |
          set -e
          mkdir -p artifacts
          START=$(date +%s)
          if [ -f "src/main.py" ]; then
            python -m src.main --crawl https://books.toscrape.com/
          else
            python -c "import requests; print(requests.get('https://httpbin.org/get', timeout=10).status_code)"
          fi
          END=$(date +%s)
          echo "$((END-START))" > artifacts/duration_s.txt
      - name: Build metrics.json (prefer real, fallback safe)
        shell: bash
        run: python scripts/generate_metrics.py
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with: { name: nightly-artifacts, path: artifacts }
      - name: Open issue on threshold breach
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const m = JSON.parse(fs.readFileSync('artifacts/metrics.json','utf8'));
            const th = { success_min: 0.90, rate_limit_max: 0.05, server_error_max: 0.03 };
            let breaches = [];
            if ((m.success_rate ?? 1) < th.success_min) breaches.push(`Success ${m.success_rate} < ${th.success_min}`);
            if ((m.rate_limit_rate ?? 0) > th.rate_limit_max) breaches.push(`429 ${m.rate_limit_rate} > ${th.rate_limit_max}`);
            if ((m.server_error_rate ?? 0) > th.server_error_max) breaches.push(`5xx ${m.server_error_rate} > ${th.server_error_max}`);
            if (breaches.length) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Nightly thresholds breached (${new Date().toISOString()})`,
                body: `Métricas:\n\`\`\`json\n${JSON.stringify(m,null,2)}\n\`\`\`\nBrechas: ${breaches.join('; ')}`,
                labels: ["type/bug","prio/P1-soon","area/orchestrator","ci"]
              });
            }
